### ISSUE TITLE
some errro when init ipc_shm_data_t.process_slots[].process_type in ipc_scrape_proctitle()

### ISSUE THREAD

**Issue by sqlfocus** [slact/ngx_lua_ipc#2]
in ipc_scrape_proctitle(),  ipc_shm_data_t.process_slots[].process_type will be 0(IPC_NGX_PROCESS_WORKER) NOT IPC_NGX_PROCESS_UNKNOWN,  for some NGX_MAX_HELPER_PROCESSES.    

ipc.broadcast() will send two more ipc msg to slot 0?

**Comment by sqlfocus** [comment]
thank your great job; diff in pull request https://github.com/slact/ngx_lua_ipc/pull/3

**Comment by slact** [comment]
Can you give me an example config where this happens? I don't quite understand what you mean by 

 >  for some NGX_MAX_HELPER_PROCESSES

**Comment by sqlfocus** [comment]
in line26 of ipc.c,  #define NGX_MAX_HELPER_PROCESSES 2
ipc_shm_data_t->max_process_count = "real worker num" + NGX_MAX_HELPER_PROCESSES
when init module, create ipc_shm_data_t->process_slots, number also ipc_shm_data_t->max_process_count, but until the end of init worker, the "NGX_MAX_HELPER_PROCESSES" slot NOT init, whose "->process_type" and "->slot" be 0, for "->process_type" it is IPC_NGX_PROCESS_WORKER.

when call ipc.broadcast(), in ipc_alert_all_processes(), the condition "if(type == IPC_NGX_PROCESS_ANY || shdata->process_slots[i].process_type == type)" will be true, if "slot=0" is used( which always worker 0); so, two more msg will be broadcast

**Comment by sqlfocus** [comment]
I use this module in openresty, just config normal workers, no other helper process

**Comment by slact** [comment]
fixed in master, thanks for the bug report!
