### ISSUE TITLE
exist some bug in ipc_hacktimer, which results worker exit every 10000s ???

### ISSUE THREAD

**Issue by sqlfocus** [slact/ngx_lua_ipc#4]
this is the error message, i will recheck the logic of program next week; if you know it, fix it: 

rocess: /tmp/src/ngx_lua_ipc/src/ngx_lua_ipc.c:181: ngx_lua_ipc_hacktimer_add_and_hack: Assertion `hacktimer == ((void *)0)' failed
2017/06/16 15:19:47 [alert] 2818#0: worker process 74660 exited on signal 6

**Comment by slact** [comment]
Just fixed in master (commit e5e3c10). The assert that was getting triggered is no longer needed.

**Comment by sqlfocus** [comment]
thank you!
