### ISSUE TITLE
write race conflict?

### ISSUE THREAD

**Issue by huyuguang** [slact/ngx_lua_ipc#5]
If two worker processes (pid1, pid2) call ipc_alert_pid(ipc, pid0...) at same time,  the ipc_write_iovec() call writev() to same fd, maybe would cause data out of order?

**Comment by huyuguang** [comment]
It seems writev() is atomic.

**Comment by slact** [comment]
Yes, writev() is atomic for 4K or less of data, which is the maximum size for the internal IPC packets.

**Comment by huyuguang** [comment]
ipc.c, line 380, is the 

> expected_iovec_sz

 always equal 

> expected_len

?

the code looks weird:

```
static ngx_int_t ipc_write_iovec(ipc_t *ipc, ngx_socket_t fd, ipc_iovec_t *vec) {
  int          n;
  int expected_iovec_sz = ipc_iovec_sz(vec->iov, vec->n);
  int expected_len = sizeof(ipc_packet_header_t) + ((ipc_packet_header_t *)vec->iov[0].iov_base)->pkt_len;
  n = writev(fd, vec->iov, vec->n);
  if (n == -1 && (ngx_errno) == NGX_EAGAIN) {
    //ngx_log_error(NGX_LOG_ALERT, ngx_cycle->log, err, "write() EAGAINED...");
    return NGX_AGAIN;
  }
  else if(n != expected_iovec_sz) {
    ERR(ipc, "writev() failed with n=%i, expected %i", n, expected_iovec_sz);
    return NGX_ERROR;
  }
  else if(n != expected_len) {
    ERR(ipc, "writev() inconsistent, expected %i, got %i", expected_len, n);
    return NGX_ERROR;
  }
  //DBG("wrote %i byte pkt", n);
  if(ipc->track_stats)
    UPDATE_STAT(ipc, packets_sent, 1);
  return NGX_OK;
}
```

**Comment by slact** [comment]
The size checks and packet splitting happen [here](https://github.com/slact/ngx_lua_ipc/blob/master/src/ipc.c#L844-L896)

**Comment by huyuguang** [comment]
I got it, very thanks.

**Comment by huyuguang** [comment]
It seems if use IPC_SOCKETPAIR and change the socketpair type from SOCK_STREAM to SOCK_SEQPACKET, the writev will always atomic?
